.TH "AFNI" "1" "June 2009" "Michael Hanke" ""
.SH "NAME"
afni \- toolkit for analyzing and visualizing functional MRI data
.SH "DESCRIPTION"
\fBAFNI\fR is an environment for processing and displaying functional MRI data.
It provides a complete analysis toolchain, including 3D cortical surface
models, and mapping of volumetric data (SUMA).

\fBAFNI\fR can be configured using either a config file or via a large
set of environment variables (see README.environment for more information).
A default configuration for POSIX-compliant environments is available in
/etc/afni/afni.sh. This is shell script that needs to be sourced. One way
to do this automatically is to add a line containing
.IP
 \. /etc/afni/afni.sh
.PP
to the .bashrc file in a users home directory (or a corresponding file
for other shells than bash).
.PP
Questions regarding the usage of \fBAFNI\fR or related theory can be
posted in the
\fBAFNI forum\fR (see \fIhttp://afni.nimh.nih.gov/afni/community/board\fR).
.SH MISSING 3DEDGE LIBRARY
3degde and its underlying library lib3dedge are covered by a license that
forbids distribution of its source code, hence cannot be part of the Debian
package. This removal has an impact on some tools in AFNI, since they make use
of this functionality be default. The Debian package has modified these tools
to allow disabling lib3degde. However, to make this modification visible the
default has NOT been changed and these option need to be given manually.

.TP
for align_epi_anat.py add options:
-skullstrip_opts -no_use_edge

.TP
for @auto_tlrc add:
-no_use_edge

.TP
for 3dSkullStrip add:
-no_use_edge

Moreover, for this tools it is not possible to use the -push_to_edge options.
.SH "FILES"
.IP /etc/afni/afni.sh
.IP /usr/share/doc/afni-common/README.environment.gz
.SH "SEE ALSO"
The AFNI homepage at
.I http://afni.nimh.nih.gov
.SH "AUTHOR"
\fBAFNI\fR was written by Robert W. Cox, and many more people.
.PP
This manual page was written by Michael Hanke <michael.hanke@gmail.com>,
for the Debian project (but may be used by others).
